project:
  type: website

website:
  title: "Alfred Cheung"
  navbar:
    left:
      - text: Project
        menu:
          - href: FYP.qmd
            text: Final Year Project
          - href: course_Project.qmd
            text: course Project
      - href: cv.qmd
        text: CV

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



