project:
  type: website

website:
  title: "Alfred Cheung"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: FYP.qmd
        text: FYP
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



